project_id = "xvtglebdgoxqwxunjrqs"

[functions.approve-admin-access]
verify_jwt = false

[functions.send-admin-verification]
verify_jwt = false

[functions.verify-admin-code]
verify_jwt = false

[functions.check-email-verification]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.submit-response]
verify_jwt = false

[functions.run-draw]
verify_jwt = true

[functions.generate-api-key]
verify_jwt = true

[functions.api-get-audits]
verify_jwt = false

[functions.api-submit-response]
verify_jwt = false
